server:
  port: 38080

spring:
  profiles:
    default: dev

  application:
    name: task-provider
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        enabled: true
        register: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  jpa:
    database: postgresql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: NONE
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false